In [1]:
!pip install numpy

Defaulting to user installation because normal site-packages is not writeable
     |████████████████████████████████| 14.8 MB 247 kB/s eta 0:00:01    |█▉                              | 829 kB 6.9 MB/s eta 0:00:03     |████████████████████▍           | 9.4 MB 2.6 MB/s eta 0:00:03     |██████████████████████          | 10.2 MB 2.6 MB/s eta 0:00:02
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.


# Numerical python End To End i Detail



Numpy:

Numpy- is a Numerical Python

It is developed by Travis Oliphant in 2005

Numpy has functions to work on linear algebra, fourier transform, and matrices

Its basically used to work with array, It can work with multidimentional Arrays


Why:

Numpy is built using python, and most of the part which requires fatser execution is developed using c or c++,So it is very fast in execution.

Numpy arrays are called as ndarray

Numpy has 50x speed as compared to python list

Numpy provides lots of functions which can be performed on large data

Numpy gives faster response as compared to list as it stores numpy arrays at one continuous location

Numpy codes are available at: https://github.com/numpy/numpy


In [1]:
import numpy as np
np.__version__

'1.19.5'

In [2]:
# create numpy array using list
arr = np.array([1,2,3,4,5,6,78,9])

print(arr)
print(type(arr))

list1 = [10,20,30,40,50]

arr1 = np.array(list1)
print(arr1)
print(type(arr1))


[ 1  2  3  4  5  6 78  9]
<class 'numpy.ndarray'>
[10 20 30 40 50]
<class 'numpy.ndarray'>


In [3]:
# how to access the element 
# its 1D array

arr = np.array([1,2,4,5,6,7])
print(arr)

#lets check the diamensions of the array
print("Number of Diamensions:",arr.ndim)

[1 2 4 5 6 7]
Number of Diamensions: 1


In [4]:
#created numpy array using tuple

tup =(1,2,3,4,5,6)
print(tup)
print(type(tup))

arr =np.array(tup)
print(arr)
print(type(arr))
print("diamensions:",arr.ndim)

(1, 2, 3, 4, 5, 6)
<class 'tuple'>
[1 2 3 4 5 6]
<class 'numpy.ndarray'>
diamensions: 1


In [5]:
#0-D array
arr = np.array(10)
print(arr)
print(type(arr))

print("Dimensions:",arr.ndim)

10
<class 'numpy.ndarray'>
Dimensions: 0


In [6]:
# 1=D array

arr = np.array((1,2,34,5,6,7))
print(arr)
print(type(arr))

print("Dimensions:",arr.ndim)

print("print the 4th loc no.",arr[4])

[ 1  2 34  5  6  7]
<class 'numpy.ndarray'>
Dimensions: 1
print the 4th loc no. 6


In [7]:
# 2-D Array

ar = [[1,2,3,4],[5,6,7,8]]
arr = np.array(ar)
print(arr)
print(type(arr))

print("Dimensions:",arr.ndim)

[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>
Dimensions: 2


In [8]:
# Access the element of 2-D array
# one way is to write


print(arr[0])
print(arr[0][2])

print(arr[1])
print(arr[1][0])

print("Dimensions:",arr.ndim)

[1 2 3 4]
3
[5 6 7 8]
5
Dimensions: 2


In [9]:
#3-D array
# array that has 2-D arrays (matrices) as its elements is called 3-D array.

ar = [[[1,2,3,4],[5,6,7,8]],[[10,20,30,40],[50,60,70,80]]]

print(type(ar))

arr = np.array(ar)

print(type(arr))
print(arr)
print("Diamentions:",arr.ndim)

<class 'list'>
<class 'numpy.ndarray'>
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[10 20 30 40]
  [50 60 70 80]]]
Diamentions: 3


In [10]:
print(arr[0][0][1])
print(arr[1][0][1])
print(arr[0][1][1])
print(arr[1][1][1])

print(arr[1])
print(arr[0,1])
      

2
20
6
60
[[10 20 30 40]
 [50 60 70 80]]
[5 6 7 8]


In [11]:
# create an n diamentional array
arr = np.array([1,2,3,4],ndmin=5)

print(arr)
print("number of diamensions :",arr.ndim)

[[[[[1 2 3 4]]]]]
number of diamensions : 5


# Array Slicing

In [12]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

#slice
print("length :",len(arr))
print(arr[0:9])

#[start:end], start included, end excluded

[1 2 3 4 5 6 7 8 9]
length : 9
[1 2 3 4 5 6 7 8 9]


In [13]:
print(arr[0:4])

[1 2 3 4]


In [14]:
print(arr[4:])

[5 6 7 8 9]


# Negative Indices

In [15]:
print(arr[-1])

9


In [16]:

print(arr)
print(arr[-9])

[1 2 3 4 5 6 7 8 9]
1


In [17]:
# step value in slicing a Numpy array
print(arr)
print(arr[0:9:3])   

[1 2 3 4 5 6 7 8 9]
[1 4 7]


In [18]:
print(arr[::2])
print(arr[0:6:2])

[1 3 5 7 9]
[1 3 5]


# Slicing of 2_D Array

In [19]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

print(arr)

print("\n")
      
print(arr[0])      
print(arr[1]) 
print(arr[0,1])  

print(arr[1,1:6]) 
print(arr[0,1:4])     

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


[1 2 3 4 5]
[ 6  7  8  9 10]
2
[ 7  8  9 10]
[2 3 4]


In [20]:
print(arr[0:3,0:4])     

[[1 2 3 4]
 [6 7 8 9]]


In [21]:
print(arr[0:2,2])     

[3 8]


In [22]:
arr= np.array([[1,2,3,4,5],[10,20,30,40,50],[11,22,33,44,55]])

print(arr)
print("Diamensions:",arr.ndim)
print(arr.size)
print(arr.shape)

[[ 1  2  3  4  5]
 [10 20 30 40 50]
 [11 22 33 44 55]]
Diamensions: 2
15
(3, 5)


In [23]:
print(arr[0:2,1:3])

[[ 2  3]
 [20 30]]


In [24]:
print(arr[1:3,1:2])

[[20]
 [22]]


In [25]:
print(arr[2:3,2:5])

[[33 44 55]]


# Data Type In Numpy

In [26]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


In [27]:
arr = np.array(["red,blue,orange,green"])
print(arr)
print(arr.dtype)

['red,blue,orange,green']
<U21


In [28]:
# creating arrays with defined data type
arr = np.array([1,2,3,4,5],dtype="int")
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


In [29]:
arr = np.array([1,2,3,4,5],dtype="float")
print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5.]
float64


In [30]:
# int with 4 bytes

arr = np.array([1,2,3,4,5],dtype="i4")
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [31]:

arr = np.array([1,2,3,4,5],dtype="i")
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [32]:
#Error
arr = np.array([1,2,3,4,5],dtype=i) #"i"
print(arr)
print(arr.dtype)

NameError: name 'i' is not defined

# Data Conversion

In [33]:
# Float into int

arr = np.array([10.1,20.9,30.3,40.1,50.6])

print(arr)

newarr = arr.astype("int")

print(newarr)
print(newarr.dtype)

[10.1 20.9 30.3 40.1 50.6]
[10 20 30 40 50]
int64


In [34]:
# int to bool

arr = np.array([0,2,0,4,5])

newarr = arr.astype("bool")

print(newarr)
print(newarr.dtype)

[False  True False  True  True]
bool


# Difference Between Copy And View

In [35]:
# Copy: It is going to create new instance for your values


arr = np.array([3,4,2,4,6,7])
print(arr)
print("\n")
x = arr.copy()
x[1]=100
print(x)

print(arr)

[3 4 2 4 6 7]


[  3 100   2   4   6   7]
[3 4 2 4 6 7]


In [36]:
# View


arr = np.array([10,20,30,40,50,60])
print(arr)
print("\n")
x = arr.view()
x[1]= 100

print(x)
print(arr)

[10 20 30 40 50 60]


[ 10 100  30  40  50  60]
[ 10 100  30  40  50  60]


In [37]:
arr = np.array([1,2,3,4,5])
#print(arr)

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


# Numpy Array Reshaping

In [38]:
# 1_D array to 2_D array

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(arr.size)
print(arr.shape)


newarr = arr.reshape(6,2)
newarr1 = arr.reshape(2,6)
newarr2 = arr.reshape(4,3)
newarr3 = arr.reshape(3,4)
newarr4 = arr.reshape(12,1)
newarr5 = arr.reshape(1,12)



print(newarr,"\n")
print(newarr1,"\n")
print(newarr2,"\n")
print(newarr3,"\n")
print(newarr4,"\n")
print(newarr5,"\n")



12
(12,)
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]] 

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] 

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]] 

[[ 1  2  3  4  5  6  7  8  9 10 11 12]] 



In [39]:
# Create 2_D array and convert it in 1_D array


arr = np.array([[1,2,3,4],[5,6,7,8]])

print(arr.size)
print(arr.shape)


newarr = arr.reshape(-1)

print(newarr)

8
(2, 4)
[1 2 3 4 5 6 7 8]


In [40]:
# 1_D array to 3_D array

arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(arr.size)
print(arr.shape)

newarr = arr.reshape(2,3,2)

newarr1= arr.reshape(2,2,3)

newarr2= arr.reshape(3,2,2)


print(newarr,"\n")
print(newarr1,"\n")
print(newarr2,"\n")
      
print("Diamentions :",newarr.ndim)


12
(12,)
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]] 

Diamentions : 3


In [41]:
#Create 3_d array and it convert in 1_D array

arr = np.array([[[1,2,3,4],[5,6,7,8]],[[10,20,30,40],[50,60,70,80]]])

print(arr.size)
print(arr.shape)

newarr = arr.reshape(-1)


16
(2, 2, 4)


# Unknown Dimension

In [42]:
# If user dont know any one dimension out 3 diamensions then Numpy can obtain it for user.
# User have mention the -1 for that dim.

arr = np.array([1,2,3,4,5,6,7,8])

newarr = arr.reshape(2,2,-1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# Flattening an arrays

In [43]:
# If you want to obtain a 1-D array using N-D array then reshape(-1)
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr.shape)

newarr = arr.reshape(-1)
print(newarr)
print(newarr.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[1 2 3 4 5 6 7 8]
(8,)


# Numpy Array Iterating

In [44]:
# Iteraing : means that you going through each element of that array

arr = np.array([1,2,3,4])

for x in arr:
    print(x)

1
2
3
4


In [45]:
#  Iterating on 2_D array
arr = np.array([[1,2,3,4],[5,6,7,8]])

for x in arr:
    print(x)

[1 2 3 4]
[5 6 7 8]


In [46]:
# Iterating on scalar element of the 2_D array

arr = np.array([[1,2,3],[4,5,6]])

for x in arr:
    print(x)
    
    for y in x:
        print(y)

[1 2 3]
1
2
3
[4 5 6]
4
5
6


In [47]:
# Iterating on scalar element of the 3_D array

arr  = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr.ndim)

for x in arr:
    print(x,"\n")
    for y in x:
        print(y,"\n")
        for z in y:
            print(z,"\n")


3
[[1 2 3]
 [4 5 6]] 

[1 2 3] 

1 

2 

3 

[4 5 6] 

4 

5 

6 

[[ 7  8  9]
 [10 11 12]] 

[7 8 9] 

7 

8 

9 

[10 11 12] 

10 

11 

12 



In [48]:
# Iterating on each element oh the array

arr  = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

for x in arr:
    for y in x:
        for z in y:
            print(z)

1
2
3
4
5
6
7
8
9
10
11
12


# Iterator Array Using nditer

In [49]:
arr  = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

y = np.nditer(arr)

for x in y:
    print(x)

1
2
3
4
5
6
7
8
9
10
11
12


In [50]:
# casting array element from one type to other data type
arr = np.array([1,2,3,4])


for x in np.nditer(arr,flags=["buffered"],op_dtypes=["U"]):
    print(x)
print("\n")

for x in np.nditer(arr,flags=["buffered"],op_dtypes=["float"]) :
    print(x)
print("\n") 

for x in np.nditer(arr,flags=["buffered"],op_dtypes=["S"]):
    print(x)
    

1
2
3
4


1.0
2.0
3.0
4.0


b'1'
b'2'
b'3'
b'4'


In [51]:
# slicing of an numpy array  and steps in iteration
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
    print(x) 

1
3
5
7


# Iteration Using ndenumerate()

In [52]:
# Enumeration means mentioning sequence number of somethings
# one by one.

arr = np.array([1,2,3,4])

for id,x in np.ndenumerate(arr):
    print(id,x)

(0,) 1
(1,) 2
(2,) 3
(3,) 4


In [53]:
# 2_D array

arr = np.array([[1,3,2,4],[6,5,8,7]])

for id,x in np.ndenumerate(arr):
    print(id,x)

(0, 0) 1
(0, 1) 3
(0, 2) 2
(0, 3) 4
(1, 0) 6
(1, 1) 5
(1, 2) 8
(1, 3) 7


# Joining Array

In [54]:
arr1 = np.array([10,20,30])

arr2 = np.array([1,2,3,4])

arr3 = np.concatenate((arr1,arr2))

print(arr3)

[10 20 30  1  2  3  4]


In [55]:
# Array concatenation using axis option

arr1 = np.array([[1,2,3],[4,5,6]])

arr2 = np.array([[7,8,9],[10,11,12]])


arr = np.concatenate((arr1,arr2), axis = 0)
print(arr)
print("\n")


arr = np.concatenate((arr1,arr2),axis=1)
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


# Joining Arrays using Stack Function

Stacking is same as concatenation, the only difference is that stacking is done along a new axis.

In [56]:
arr1 = np.array([[1,2,3],[4,5,6]])

arr2 = np.array([[7,8,9],[10,11,12]])


arr = np.stack((arr1,arr2), axis = 0)
print(arr)
#print("\n")


arr = np.stack((arr1,arr2),axis=1)
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]


In [57]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr) 

arr = np.stack((arr1, arr2), axis=0)

print(arr) 


[[1 4]
 [2 5]
 [3 6]]
[[1 2 3]
 [4 5 6]]


In [58]:
# hstack
arr1= np.array([1,2,3,4])

arr2 = np.array([5,6,7,8])

arr = np.hstack((arr1,arr2))

print(arr)
print(arr.shape)

[1 2 3 4 5 6 7 8]
(8,)


In [59]:
# vstack  (along with the coloumn)
arr1= np.array([1,2,3,4])

arr2 = np.array([5,6,7,8])

arr = np.vstack((arr1,arr2))

print(arr)
print(arr.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [60]:
# dstack (along with the depth)
arr1= np.array([1,2,3,4])

arr2 = np.array([5,6,7,8])

arr = np.dstack((arr1,arr2))

print(arr)
print(arr.shape)

[[[1 5]
  [2 6]
  [3 7]
  [4 8]]]
(1, 4, 2)


# Splitting Array

In [61]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr)

newarr = np.split(arr,3)
print(newarr)


for i in newarr:
    print(i)

[1 2 3 4 5 6 7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
[1 2 3]
[4 5 6]
[7 8 9]


In [62]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

newarr = np.split(arr,3,axis=1)
print(newarr)

for i in newarr:
    print(i)

[[1 2 3]
 [4 5 6]]
[array([[1],
       [4]]), array([[2],
       [5]]), array([[3],
       [6]])]
[[1]
 [4]]
[[2]
 [5]]
[[3]
 [6]]


In [63]:
# If no.of elements less then it adjust in last array

arr = np.array([1,2,3,4,5,6,7])

#print(arr)

newarr = np.array_split(arr,6)
print(newarr)

[array([1, 2]), array([3]), array([4]), array([5]), array([6]), array([7])]


In [64]:
arr = np.array([1,2,3,4,5,6,7,8])

newarr = np.array_split(arr,3)
print(newarr)
print(newarr[1])
print(newarr[2])

[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]
[4 5 6]
[7 8]


In [65]:
#splitting on 2_D Array

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

newarr = np.array_split(arr,2,axis=1)

for i in newarr:
    print(i,"\n")

[[1 2]
 [4 5]
 [7 8]] 

[[3]
 [6]
 [9]] 



In [66]:
# Array splitting on axis
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

newarr = np.array_split(arr,2,axis=0)


print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[7, 8, 9]])]


# Using hsplit() opposite of hstack()

In [67]:
arr = np.array([[1,20],[2,3],[4,5],[6,7],[8,9]])

newarr = np.hsplit(arr,2)
print(newarr)

[array([[1],
       [2],
       [4],
       [6],
       [8]]), array([[20],
       [ 3],
       [ 5],
       [ 7],
       [ 9]])]


# Searching Arrays

In [68]:
# Finding element in 1_D

arr = np.array([1,2,3,45,3,6,1,9])


x = np.where(arr == 45)
print(arr)
print("location :",x)

[ 1  2  3 45  3  6  1  9]
location : (array([3]),)


In [69]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 5)

print(arr)
print("Location : ",x)


[1 2 3 4 5 4 4]
Location :  (array([4]),)


In [70]:
# Arithmetic operations on numpy array
arr = np.array([[1,2,3,4],[5,6,7,8]])
print(arr)


print("\n Addition :\n",arr+2)
print("\n Substraction :\n",arr-2)
print("\n Multiplication :\n",arr*2)
print("\n Division :\n",arr/0.5)

[[1 2 3 4]
 [5 6 7 8]]

 Addition :
 [[ 3  4  5  6]
 [ 7  8  9 10]]

 Substraction :
 [[-1  0  1  2]
 [ 3  4  5  6]]

 Multiplication :
 [[ 2  4  6  8]
 [10 12 14 16]]

 Division :
 [[ 2.  4.  6.  8.]
 [10. 12. 14. 16.]]


In [71]:
# Find the location of even number  in my numpy array

arr = np.array([1,2,3,4,5,6,7,8,9])

x = np.where(arr%2 == 0)

print(x)

(array([1, 3, 5, 7]),)


In [72]:
# Find the location of odd number  in my numpy array
arr = np.array([1,2,3,4,5,6,7,8,9])

x = np.where(arr%2 == 1)

print("Locations :",x)

Locations : (array([0, 2, 4, 6, 8]),)


# Searchsorted()

In [73]:
# performs a binary search in the array, and returns the index 
# where the specified value would be inserted to maintain 
# the search order.

# this method does not insert element , 
# it just returns a location for element in the numpy array


arr = np.array([2,5,4,7,8,3])

loc = np.searchsorted(arr,7, side="left")

print(arr)
print("Location where element to be inserted:",loc)

[2 5 4 7 8 3]
Location where element to be inserted: 3


In [74]:
#side
loc = np.searchsorted(arr,2.5, side="left")

print(arr)
print("Location where element to be inserted:",loc)


[2 5 4 7 8 3]
Location where element to be inserted: 1


In [75]:
# multiple values
arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 8, 6])

print(x) 


[1 4 3]


# Sorting Arrays

Sorting means putting elements in an ordered sequence.Like numeric or alphabetical,ascending or descending.

sort(), that will sort specified array

In [76]:
# sort() on numerical arrays

arr = np.array([4,7,1,3,9])

res = np.sort(arr)

print(arr)
print(res)

[4 7 1 3 9]
[1 3 4 7 9]


In [77]:
#sort() on string array

arr = np.array(["red","blue","yellow","green"])

res = np.sort(arr)

print(arr,"\n")

print(res)

['red' 'blue' 'yellow' 'green'] 

['blue' 'green' 'red' 'yellow']


In [78]:
# sort() on boolean values

arr = np.array([True,True,False,True,False ])
res = np.sort(arr)

print(arr,"\n")
print(res)

[ True  True False  True False] 

[False False  True  True  True]


In [79]:
# sort on 2_D array

arr = np.array([[1,7,3],[2,9,4]])

res = np.sort(arr)
print(arr,"\n")
print(res)

print("\n")
#Working on axis 
#axis=0
print("Sorting on 0 axis :\n",arr)
res = np.sort(arr,axis=0)
print(res)

#axis = 1
print("\n")
print("Sorting on 1 axis :\n",arr)
res = np.sort(arr,axis=1)
print(res)

[[1 7 3]
 [2 9 4]] 

[[1 3 7]
 [2 4 9]]


Sorting on 0 axis :
 [[1 7 3]
 [2 9 4]]
[[1 7 3]
 [2 9 4]]


Sorting on 1 axis :
 [[1 7 3]
 [2 9 4]]
[[1 3 7]
 [2 4 9]]


# Filter Array

Getting some element out of an existing array and creating a new array out of them is called filtering.

Numpy filter an array using a boolean index list.

A boolean index list is alist of booleans corresponding to indexes in the array.

In [80]:
arr =np.array([1,2,3,4,5,6])

x = [False,True,True,False,True,False]

newarr = arr[x]

print(arr,"\n")
print(newarr)

[1 2 3 4 5 6] 

[2 3 5]


In [81]:
arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr)
# Create an empty list
index = []

# go through each element in arr
for i in arr:
    
  # if the element is higher than 4, set the value to True, otherwise False:
    if i > 4:
        index.append(True)
    else:
        index.append(False)

print(index)

newarr = arr[index]

print(newarr)

[1 2 3 4 5 6 7 8 9]
[False, False, False, False, True, True, True, True, True]
[5 6 7 8 9]


In [82]:
# Print a  list of even numbers from origial list using array filter

arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr)

index = []
#i%2==0

for i in arr:
    if i%2==0:
        index.append(True)
        
    else:
        index.append(False)
        
print(index) 

newarr = arr[index]
print(newarr)

[1 2 3 4 5 6 7 8 9]
[False, True, False, True, False, True, False, True, False]
[2 4 6 8]


In [83]:
# Print a  list of odd numbers from origial list using array filter

arr = np.array([1,2,3,4,5,6,7,8,9])

print(arr)

index = []
#i%2==0

for i in arr:
    if i%2==1:
        index.append(True)
        
    else:
        index.append(False)
        
print(index) 

newarr = arr[index]
print(newarr)

[1 2 3 4 5 6 7 8 9]
[True, False, True, False, True, False, True, False, True]
[1 3 5 7 9]


In [84]:
arr = np.array([12,23,45,67])

filter_arr = arr > 23

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)


[False False  True  True]
[45 67]


In [85]:
arr = np.array([1,2,3,4,56,7,89])

filter_arr = (arr % 2 ==0)

newarr  = arr[filter_arr]

print(filter_arr)

print(newarr)

[False  True False  True  True False False]
[ 2  4 56]


# Other Numpy Functions

In [86]:
arr = np.arange(20)
print(arr)
print(type(arr))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
<class 'numpy.ndarray'>


In [87]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [88]:
#convert 2_D


print(arr)
arr_2d = np.reshape(arr,(5,4))

print(arr_2d)

arr2 = arr.reshape(5,4)
print(arr2)
print(arr2.shape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
(5, 4)


In [89]:
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [90]:
arr_2d.min()

0

In [91]:
arr_2d.max()

19

In [92]:
arr_2d.argmax()

19

In [93]:
# Indices to sort array
arr_2d.argsort()

array([[0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3],
       [0, 1, 2, 3]])

In [94]:
arr_2d.diagonal()

array([ 0,  5, 10, 15])

In [95]:
arr_2d.sum()

190

In [96]:
arr_2d.mean()

9.5

In [97]:
# Return th eindices of non zero elements
print(arr_2d)
arr_2d.nonzero()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


(array([0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4]),
 array([1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3, 0, 1, 2, 3]))

In [98]:
# Create array of 10 elements between start to end values

arr2 = np.linspace(11,34,10)

In [99]:
arr2

array([11.        , 13.55555556, 16.11111111, 18.66666667, 21.22222222,
       23.77777778, 26.33333333, 28.88888889, 31.44444444, 34.        ])

In [101]:
#Flatten array

print(arr_2d)
arr_2d.ravel()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [104]:
# Create array with random element

arr = np.random.randn(4,3)
arr

array([[ 0.12314718,  0.29775498, -0.38201044],
       [ 1.05781019,  0.44561866,  0.16749099],
       [-0.91486994,  0.22112874,  1.7693209 ],
       [-0.50041598, -0.07986632,  0.79804933]])

In [105]:
# Unit matrix
arr = np.eye(4,4)
print(arr)

arr2 = np.eye(5,5,3)
print(arr2)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [106]:
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [109]:
arr =np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [110]:
arr=np.diag([3,3,3,3])
arr

array([[3, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 3]])

In [113]:
arr1 = np.arange(1,5)
arr2 = np.arange(1,5)
print(arr1)
print(arr2)

[1 2 3 4]
[1 2 3 4]


In [114]:
ar1 =arr1.reshape(2,2)
ar2 =arr2.reshape(2,2)
print(ar1)
print(ar2)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [115]:
ar1.dot(ar2)

array([[ 7, 10],
       [15, 22]])

In [ ]:
ar1*